version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "▶ Instalando dependencias..."
      - npm install -g serverless@3.38.0
      - npm install

      - echo "▶ Inicializando repo Git temporal..."
      - git init
      - git add .
      - git commit -m "Scan commit" || true  # Evita error si ya está comiteado

      - echo "▶ Instalando git-secrets..."
      - git clone https://github.com/awslabs/git-secrets.git
      - cd git-secrets && make install && cd ..

      - echo "▶ Configurando git-secrets..."
      - git secrets --install
      - git secrets --register-aws

  build:
    commands:
      - echo "▶ Ejecutando análisis de secretos con git-secrets..."
      - git secrets --scan $(find . -type f -name '*.js') || { echo '❌ Se detectaron secretos embebidos.'; exit 1; }

      - echo "✅ Sin secretos detectados. Procediendo con el despliegue..."
      - sls deploy --stage dev
