name: DAST - OWASP ZAP (Baseline)

on:
  workflow_dispatch:      # Permite ejecutarlo manualmente desde Actions
  push:                   # Lo dispara automáticamente
    branches:
      - main              # Solo cuando haces push/merge a main
  pull_request:           # (Opcional) también al abrir PRs hacia main
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.7.0
        with:
          target: "https://exvfd7r0sl.execute-api.us-east-2.amazonaws.com/dev/eventplanner/services/AddUser"
          report_file: zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: ZAP-DAST-Report
          path: zap_report.html
